print("Добрый день! Заполните анкету")
name = input("Введите Ваше имя: ")
age = int(input("Введите Ваш возраст: "))
favorite_color = input("Назовите Ваш любимый цвет: ")
favorite_animal = input("Ваше любимое животное: ")
print("\nВот что мы узнали о вас:")
print("Имя:", name)
print("Возраст:", age)
print("Любимый цвет:", favorite_color)
print("Любимое животное:", favorite_animal)